version: '3.8'

networks:
  backfront-net:

services:
  backend-nestjs:
    restart: always
    image: "node:20.9-bookworm-slim"
    env_file:
      - ./backend/.env
    working_dir: /srv/backend
    volumes:
      - ./backend/:/srv/backend
    ports:
      - 3000:3000
      - 9229:9229 # Para tests
    command: "npm run start:dev"
    networks:
      - backfront-net

  frontend-vuejs:
    image: "node:20.9-bookworm-slim"
    working_dir: /srv/frontend
    volumes:
      - ./frontend:/srv/frontend
    ports:
      - 8080:8080
      - 8081:8081
      - 4173:4173
      - 4174:4174
    command: bash -c "npm install && npm run build && npx http-server dist"
    #command: bash -c "npm install && npm run start:dev"
    networks:
      - backfront-net